In [1]:
#basic data science imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# Load Parquets

In [2]:
recipes_df = pd.read_csv('recipes.csv')
recipes_df.head(3)

,RecipeId,Name,AuthorId,AuthorName,CookTime,PrepTime,TotalTime,DatePublished,Description,Images,...,SaturatedFatContent,CholesterolContent,SodiumContent,CarbohydrateContent,FiberContent,SugarContent,ProteinContent,RecipeServings,RecipeYield,RecipeInstructions
0,38,Low-Fat Berry Blue Frozen Dessert,1533,Dancer,PT24H,PT45M,PT24H45M,1999-08-09T21:46:00Z,Make and share this Low-Fat Berry Blue Frozen ...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,1.3,8.0,29.8,37.1,3.6,30.2,3.2,4.0,NaN,"c(""Toss 2 cups berries with sugar."", ""Let stan..."
1,39,Biryani,1567,elly9812,PT25M,PT4H,PT4H25M,1999-08-29T13:12:00Z,Make and share this Biryani recipe from Food.com.,"c(""https://img.sndimg.com/food/image/upload/w_...",...,16.6,372.8,368.4,84.4,9.0,20.4,63.4,6.0,NaN,"c(""Soak saffron in warm milk for 5 minutes and..."
2,40,Best Lemonade,1566,Stephen Little,PT5M,PT30M,PT35M,1999-09-05T19:52:00Z,This is from one of my first Good House Keepi...,"c(""https://img.sndimg.com/food/image/upload/w_...",...,0.0,0.0,1.8,81.5,0.4,77.2,0.3,4.0,NaN,"c(""Into a 1 quart Jar with tight fitting lid, ..."

In [3]:
reviews_df = pd.read_csv('reviews.csv')
reviews_df.head(3)

,ReviewId,RecipeId,AuthorId,AuthorName,Rating,Review,DateSubmitted,DateModified
0,2,992,2008,gayg msft,5,better than any you can get at a restaurant!,2000-01-25T21:44:00Z,2000-01-25T21:44:00Z
1,7,4384,1634,Bill Hilbrich,4,"I cut back on the mayo, and made up the differ...",2001-10-17T16:49:59Z,2001-10-17T16:49:59Z
2,9,4523,2046,Gay Gilmore ckpt,2,i think i did something wrong because i could ...,2000-02-25T09:00:00Z,2000-02-25T09:00:00Z

In [4]:
print(f'Recipes Shape: {recipes_df.shape}')
print(f'Reviews Shape: {reviews_df.shape}')

Recipes Shape: (522517, 28)
Reviews Shape: (1401982, 8)

# Preliminary Exploration

In [5]:
# Info
recipes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 522517 entries, 0 to 522516
Data columns (total 28 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   RecipeId                    522517 non-null  int64
 1   Name                        522517 non-null  object
 2   AuthorId                    522517 non-null  int64
 3   AuthorName                  522517 non-null  object
 4   CookTime                    439972 non-null  object
 5   PrepTime                    522517 non-null  object
 6   TotalTime                   522517 non-null  object
 7   DatePublished               522517 non-null  object
 8   Description                 522512 non-null  object
 9   Images                      522516 non-null  object
 10  RecipeCategory              521766 non-null  object
 11  Keywords                    505280 non-null  object
 12  RecipeIngredientQuantities  522514 non-null  object
 13  RecipeIngredientParts       522517 non-null  object
 14  AggregatedRating            269294 non-null  float64
 15  ReviewCount                 275028 non-null  float64
 16  Calories                    522517 non-null  float64
 17  FatContent                  522517 non-null  float64
 18  SaturatedFatContent         522517 non-null  float64
 19  CholesterolContent          522517 non-null  float64
 20  SodiumContent               522517 non-null  float64
 21  CarbohydrateContent         522517 non-null  float64
 22  FiberContent                522517 non-null  float64
 23  SugarContent                522517 non-null  float64
 24  ProteinContent              522517 non-null  float64
 25  RecipeServings              339606 non-null  float64
 26  RecipeYield                 174446 non-null  object
 27  RecipeInstructions          522517 non-null  object
dtypes: float64(12), int64(2), object(14)
memory usage: 111.6+ MB

In [6]:
# Describe
recipes_df.describe().T

,count,mean,std,min,25%,50%,75%,max
RecipeId,522517.0,2.718214e+05,1.554959e+05,38.0,137206.0,271758.0,406145.0,5.413830e+05
AuthorId,522517.0,4.572585e+07,2.929714e+08,27.0,69474.0,238937.0,565828.0,2.002886e+09
AggregatedRating,269294.0,4.632014e+00,6.419341e-01,1.0,4.5,5.0,5.0,5.000000e+00
ReviewCount,275028.0,5.227784e+00,2.038135e+01,1.0,1.0,2.0,4.0,3.063000e+03
Calories,522517.0,4.844386e+02,1.397117e+03,0.0,174.2,317.1,529.1,6.128546e+05
FatContent,522517.0,2.461492e+01,1.114858e+02,0.0,5.6,13.8,27.4,6.436810e+04
SaturatedFatContent,522517.0,9.559457e+00,4.662262e+01,0.0,1.5,4.7,10.8,2.674060e+04
CholesterolContent,522517.0,8.648700e+01,3.019870e+02,0.0,3.8,42.6,107.9,1.304564e+05
SodiumContent,522517.0,7.672639e+02,4.203621e+03,0.0,123.3,353.3,792.2,1.246921e+06
CarbohydrateContent,522517.0,4.908909e+01,1.808221e+02,0.0,12.8,28.2,51.1,1.082946e+05
FiberContent,522517.0,3.843242e+00,8.603163e+00,0.0,0.8,2.2,4.6,3.012000e+03
SugarContent,522517.0,2.187825e+01,1.426202e+02,0.0,2.5,6.4,17.9,9.068230e+04
ProteinContent,522517.0,1.746951e+01,4.012884e+01,0.0,3.5,9.1,25.0,1.839620e+04
RecipeServings,339606.0,8.606191e+00,1.143198e+02,1.0,4.0,6.0,8.0,3.276700e+04

In [7]:
# Info
reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1401982 entries, 0 to 1401981
Data columns (total 8 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   ReviewId       1401982 non-null  int64
 1   RecipeId       1401982 non-null  int64
 2   AuthorId       1401982 non-null  int64
 3   AuthorName     1401982 non-null  object
 4   Rating         1401982 non-null  int64
 5   Review         1401768 non-null  object
 6   DateSubmitted  1401982 non-null  object
 7   DateModified   1401982 non-null  object
dtypes: int64(4), object(4)
memory usage: 85.6+ MB

In [8]:
# Describe
reviews_df.describe().T

,count,mean,std,min,25%,50%,75%,max
ReviewId,1401982.0,8.179739e+05,5.280821e+05,2.0,374386.25,771780.5,1204125.75,2.090347e+06
RecipeId,1401982.0,1.526412e+05,1.301112e+05,38.0,47038.75,109327.0,231876.75,5.412980e+05
AuthorId,1401982.0,1.558638e+08,5.305111e+08,1533.0,133680.00,330545.0,818359.00,2.002902e+09
Rating,1401982.0,4.407951e+00,1.272012e+00,0.0,4.00,5.0,5.00,5.000000e+00

## Is there the same number of RecipeIds in both dataframes?